### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by rlzmtnck** [officialputuid/toolsig#12]
```
? Try to Login . . .
{ [RequestError]
  name: 'RequestError',
  message: '',
  json: { message: '', status: 'fail' } }
```

gimana ni sob ?

**Comment by officialputuid** [comment]
☑ [05/12/2020] update toolsig v3
	☑ [03/12/2020] Add challenge_required request ig.
	☑ [03/12/2020] Fix Some Errors, Features and Change Instagram API Version.
