### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by MiChaelinzo** [officialputuid/toolsig#15]
❆Bot Like Timeline v1
 ❆ Bot Like Timeline v2

ERROR: Maaf, Untuk Saat Ini Bot Like Timeline v1 ERROR, Gunakan Tools Lain!
 STATUS: ERROR! Please try again!

**Comment by officialputuid** [comment]
☑ [05/12/2020] update toolsig v3
	☑ [03/12/2020] Add challenge_required request ig.
	☑ [03/12/2020] Fix Some Errors, Features and Change Instagram API Version.
