### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by J35t3rOP** [officialputuid/toolsig#36]
Hello, so every time i use a tool from the list i get this error. How can i fix it?

[?] Try to Login . . .
TypeError: Cannot read property 'Device' of undefined
    at Login (/home/kali/instafollow/src/unfollowNotFollowBack.js:52:28)
    at Excute (/home/kali/instafollow/src/unfollowNotFollowBack.js:116:25)
    at /home/kali/instafollow/src/unfollowNotFollowBack.js:160:2

**Comment by officialputuid** [comment]
Try rm -rf node_modules
Then npm install (make sure you install nodejs)

**Comment by officialputuid** [comment]
![Uploading Screenshot_20210628-223500408.jpg…]()

**Comment by officialputuid** [comment]
![Screenshot_20210628-223500408](https://user-images.githubusercontent.com/40856427/123655099-44a4a400-d861-11eb-8259-64de20c00e99.jpg)

**Comment by officialputuid** [comment]
Ok, because no response, the issue will be closed.
If you want to create a new issue, please provide proof screenshots or other related matters.

**Comment by J35t3rOP** [comment]
hello, sorry i had internet problems. it still has the same error

**Comment by officialputuid** [comment]
If you want to create a new issue, please provide proof screenshots or other related matters.
