### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by J35t3rOP** [officialputuid/toolsig#37]
![Screenshot_2021-06-30_08_54_22](https://user-images.githubusercontent.com/60807708/123908892-bebf5080-d967-11eb-8a0b-26dd6db31ed9.png)

**Comment by officialputuid** [comment]
Default or Basic Usage
$ git clone https://github.com/officialputuid/toolsig.git
$ cd toolsig
$ npm i
$ node index.js

**Comment by J35t3rOP** [comment]
i did all that and still not working

**Comment by officialputuid** [comment]
i dont see ur node_modules files

**Comment by officialputuid** [comment]
read README.md before use this tools

**Comment by J35t3rOP** [comment]
![Screenshot_2021-06-30_09_02_55](https://user-images.githubusercontent.com/60807708/123909688-e531bb80-d968-11eb-967b-0000d139f28b.png)

**Comment by J35t3rOP** [comment]
![Screenshot_2021-06-30_09_04_00](https://user-images.githubusercontent.com/60807708/123909755-00043000-d969-11eb-9454-5c55cf44b072.png)

**Comment by J35t3rOP** [comment]
![Screenshot_2021-06-30_09_05_23](https://user-images.githubusercontent.com/60807708/123909885-3477ec00-d969-11eb-8e2a-be968c192247.png)

**Comment by J35t3rOP** [comment]
i get this errors every time i try npm audit fix. nothing gets fixed

**Comment by officialputuid** [comment]
dont audit, just do like this
$ git clone https://github.com/officialputuid/toolsig.git
$ cd toolsig
$ npm i
$ node index.js

**Comment by officialputuid** [comment]
![image](https://user-images.githubusercontent.com/40856427/123910315-da991580-d9ac-11eb-8af1-182bfeebf92e.png)
