### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by niizam** [officialputuid/toolsig#38]
Why i can't login with my 2nd account?
But my main account is work smoothly

It says
`POST /api/v1/accounts/login/ - 400 Bad Request;`

Also i don't receive any verification request from Instagram

**Comment by officialputuid** [comment]
Yup, there are several account variants that cannot use this tool, such as verified Instagram accounts or have high interactions/values. need help fixing, already labeled, thanks.

**Comment by 89z** [comment]
same problem
