### ISSUE TITLE
Hastag tool follows same account all over again

### ISSUE THREAD

**Issue by J35t3rOP** [officialputuid/toolsig#39]
![Screenshot_20210722_094734](https://user-images.githubusercontent.com/60807708/126599850-d73332a1-fca9-4f8b-85b9-22155e186ba6.jpg)

**Comment by officialputuid** [comment]
Ok will check later, thx.

**Comment by officialputuid** [comment]
it's so bad, looks crazier than a bot. use the best ratio, recommended 1-5 targets in delay above 30 minutes.
