### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by SyaefulBakhri26** [officialputuid/toolsig#47]
![Screenshot_2021-10-30-07-25-57-906_com termux](https://user-images.githubusercontent.com/93412474/139513802-ba87e20a-2eb1-4835-9da7-244b6bc3753d.jpg)

**Comment by SanKazeArashi** [comment]
Same, i've got error too

**Comment by officialputuid** [comment]
use nodejs-lts, reclone and npm i again.
