### ISSUE TITLE
bug in termux

### ISSUE THREAD

**Issue by fazle-rabbi-dev** [officialputuid/toolsig#52]
![Screenshot_20220113-143647](https://user-images.githubusercontent.com/71178740/149295494-c2be6e0b-0018-4742-a814-3f20ae621d5f.png)

**Comment by fh-rabbi** [comment]
![Uploading Screenshot_20220113-143647.png…]()

**Comment by refx3** [comment]
downgrade to npm version 6 using:
`npm install -g npm@6`
then run `npm i` again.
