### ISSUE TITLE
SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by dianadeetiawan** [officialputuid/toolsig#6]
Kok begini ya?
Ubuntu 16.04

`user@ubuntu:~/toolsig$ node index.js`

/home/user/toolsig/index.js:48
const main = async() => {
                  ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by officialputuid** [comment]
Pastikan Sudah Mengikuti Tutorial Dengan Baik:
1. Tutorial on Termux [ANDROID] [https://s.id/7tOcB]
2. Tutorial on C9io/CodeAnywhere [https://s.id/7tOrU]
3. Tutorial on PC/LAPTOP [https://s.id/7tOxC]

Saya Test NodeJS di Ubuntu 16.04 CodeAnywhere Berjalan Dengan Baik!
Bukti:
![Screenshot_1](https://user-images.githubusercontent.com/40856427/67141578-890e2d00-f294-11e9-8802-d3f5dbfe9b37.png)

**Comment by dianadeetiawan** [comment]
> Pastikan Sudah Mengikuti Tutorial Dengan Baik:
> 
> 1. Tutorial on Termux [ANDROID] [https://s.id/7tOcB]
> 2. Tutorial on C9io/CodeAnywhere [https://s.id/7tOrU]
> 3. Tutorial on PC/LAPTOP [https://s.id/7tOxC]
> 
> Saya Test NodeJS di Ubuntu 16.04 CodeAnywhere Berjalan Dengan Baik!
> Bukti:
> ![Screenshot_1](https://user-images.githubusercontent.com/40856427/67141578-890e2d00-f294-11e9-8802-d3f5dbfe9b37.png)

Saya pakai sebuah VPS Unmanaged Ubuntu 16.04

solved: dengan cara menginstall nvm terlebih dahulu.
install nvm nya
> curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
lalu export path nya
> source ~/.bashrc
kemudian install seperti di cloud IDE semacam C9io/CodeAnywhere [https://s.id/7tOrU]

> nvm install 10.7.0 && nvm use 10.7.0 && nvm alias default 10.7.0

baru bisa lancar seperti berikut

![Screenshot_2019-10-20_01-26-25](https://user-images.githubusercontent.com/42414765/67149701-a82eae00-f2d8-11e9-839c-88864a487489.png)

**Comment by officialputuid** [comment]
Nah kan ketauan Ga bisa Baca Tutorial, Padahal itu udah ada di tutorial.
