### ISSUE TITLE
Stuck in: Instagram Login

### ISSUE THREAD

**Issue by kreafik** [officialputuid/toolsig#8]
Ξ TITLE  : UNFB [Unfollow Not Followback User]
  Ξ CODE   : CYBER SCREAMER CCOCOT (ccocot@bc0de.net)
  Ξ STATUS : [+ITTWY] & [TESTED]

for all of them doing this, it just keeps wait here, so i cant login my instagram acc

(working on win10, installed all of the programs.)
![image](https://user-images.githubusercontent.com/59885295/73127039-9b9ead80-3fcb-11ea-992b-b462378a9a52.png)

**Comment by officialputuid** [comment]
Use NodeJS Version in README.md

# Download & Install Git for Windows (Link Download: https://s.id/2yGtu) *direct_link
# Download & Install NodeJs for Windows (Versi 9.3.0)
  -> 64bit (https://nodejs.org/dist/v9.3.0/node-v9.3.0-x64.msi) *direct_link_64bit
  -> 32bit (https://nodejs.org/dist/v9.3.0/node-v9.3.0-x86.msi) *direct_link_32bit
# Download File toolsig (https://s.id/2yGC6) & Extract the file
# Right Click (Mouse/Touchpad) In "toolsig-master" Folder & Choose Git Bash Here!
$ unzip lib.zip
$ node index.js
